---
volumes:
  postgres-data:
    driver: "local"
services:
  postgres:
    build:
      dockerfile: ./Dockerfile
      context: postgres
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres:${TAG_NAME}
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./postgres/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  hato-bot:
    build:
      dockerfile: ./Dockerfile
      context: .
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/commit-hash:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/commit-hash
      args:
        BUILDKIT_INLINE_CACHE: 1
      x-bake:
        platforms:
          - linux/amd64
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot:${TAG_NAME}
    platform: linux/amd64
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
