---
version: "3.7"
volumes:
  pgsql-data:
    driver: "local"
services:
  postgres:
    build:
      dockerfile: ./Dockerfile
      context: ./pgsql
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./pgsql-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  hato-bot:
    build:
      dockerfile: ./Dockerfile
      context: ../
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
