---
version: "3.7"
volumes:
  pgsql-data:
    driver: "local"
services:
  postgres:
    build:
      dockerfile: ./Dockerfile
      context: pgsql
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/postgres:${TAG_NAME}
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./pgsql-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  hato-bot:
    build:
      dockerfile: ./Dockerfile
      context: ../
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot:${TAG_NAME}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot
      x-bake:
        platforms:
          - linux/amd64
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-bot}/hato-bot:${TAG_NAME}
    platform: linux/amd64
    env_file:
      - ../.env
    restart: always
    volumes:
      - ../:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
