name: Add to Task List
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
jobs:
  add-to-task-list:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1.10.1
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-add-to-projects@29c8fe72714985ca857a780c1596fb038fc59921 # v0.0.73
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          project-url: https://github.com/orgs/dev-hato/projects/1
