name: Add to Task List
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
jobs:
  add-to-task-list:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-add-to-projects@dfe16998dd3ae5ae61049fd8cf1d8f0d42a124c1 # v0.0.64
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          project-url: https://github.com/orgs/dev-hato/projects/1
