name: Add to Task List
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
jobs:
  add-to-task-list:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c # v1.9.0
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-add-to-projects@c6704fc7d5a5932da7524cdd0ab7b1feb96dd493 # v0.0.62
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          project-url: https://github.com/orgs/dev-hato/projects/1
