name: Add to Task List
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
jobs:
  add-to-task-list:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.repository == github.event.pull_request.head.repo.full_name
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@bf627a5a4415baceb13b8feb7cdbe1f4b112dc8d # v1.8.2
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-add-to-projects@3b83c3bd1c50fa440bccfcdd85b3f74120e70804 # v0.0.61
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          project-url: https://github.com/orgs/dev-hato/projects/1
