---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - develop
      - master
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
permissions:
  actions: write
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dev-hato/github-actions-cache-cleaner@7998d4147fd721e643ef405311038ae5d67b40ce # v0.0.92
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
