---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - develop
      - master
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
permissions:
  actions: write
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dev-hato/github-actions-cache-cleaner@1ba646617cec6f0ba43f65d66ce81b45b94e20a5 # v0.0.88
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
