---
name: pr-close-hato-bot

on:
  pull_request:
    types:
      - closed

jobs:
  # PR close時にCIが出したPRをcloseする
  pr-close-hato-bot:
    runs-on: ubuntu-latest

    steps:
      - run: |
          REPO_NAME="${{ github.event.pull_request.head.repo.full_name }}"
          echo "REPO_NAME=${REPO_NAME}" >> "${GITHUB_ENV}"
      - name: Close PullRequest
        uses: actions/github-script@v6
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        if: env.REPO_NAME == github.repository
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const HEAD_REF = process.env["HEAD_REF"]
            const common_params = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }

            for (const head_name of ["yarn-" + HEAD_REF,
                                     "fix-format-" + HEAD_REF,
                                     "fix-version-pre-commit-config-" + HEAD_REF,
                                     "fix-version-" + HEAD_REF + "-python-version"]) {
              let head = "${{github.event.pull_request.head.repo.owner.login}}:"
              head += head_name
              const pulls_list_params = {
                head,
                base: HEAD_REF,
                state: "open",
                ...common_params
              }
              console.log("call pulls.list:", pulls_list_params)
              const pulls = await github.paginate(github.rest.pulls.list,
                                                  pulls_list_params)

              for (const pull of pulls) {
                const pulls_update_params = {
                  pull_number: pull.number,
                  state: "closed",
                  ...common_params
                }
                console.log("call pulls.update:", pulls_update_params)
                await github.rest.pulls.update(pulls_update_params)
                const git_deleteRef_params = {
                  ref: "heads/" + head_name,
                  ...common_params
                }
                console.log("call git.deleteRef:", git_deleteRef_params)
                await github.rest.git.deleteRef(git_deleteRef_params)
              }
            }
