---
name: pr-test-hato-bot
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop
jobs:
  # unittestを行う
  # testが落ちたらチェックが落ちる
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: "recursive"
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          enable-cache: true
      - name: Install dependencies
        run: bash "${GITHUB_WORKSPACE}/scripts/uv_install.sh"
      - name: Test
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_test_hato_bot/pr_test/test.sh"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
