---
name: pr-test-hato-bot
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop
permissions: {}
jobs:
  # unittestを行う
  # testが落ちたらチェックが落ちる
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: "recursive"
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: bash "${GITHUB_WORKSPACE}/scripts/uv_install.sh"
      - name: Test
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_test_hato_bot/pr_test/test.sh"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
