---
name: pr-update-gitleaks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - develop
      - master
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  pr-update-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          cache: npm
          node-version-file: package.json
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
      - run: npm install -g "$(yq -r '.packageManager' package.json)"
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - name: Install packages
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: npm ci
      - uses: dev-hato/actions-update-gitleaks@935a6b48ba0466536e0b1582f0724ac34cd093e9 # v0.0.110
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
