---
name: update-python-hato-bot

on:
  pull_request:

jobs:
  # .python-version をDockerイメージと同期させる
  update-version-python-version:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          exit_code=1

          for i in $(seq 600); do
            docker-compose pull
            exit_code=${?}

            if [ ${exit_code} -eq 0 ]; then
              break
            fi

            sleep 1
          done

          exit ${exit_code}
        working-directory: setup
      - name: Get Python version
        id: get_python_version
        working-directory: setup
        run: |
          DOCKER_CMD="python --version 2>&1 | sed -e 's/^Python //g'"
          python_version=$(docker-compose run hato-bot sh -c "${DOCKER_CMD}")
          echo "Python version:" "${python_version}"
          echo "::set-output name=python_version::${python_version}"
      - name: Update versions
        run: |
          PYTHON_VERSION="${{steps.get_python_version.outputs.python_version}}"
          echo "${PYTHON_VERSION}" > .python-version
      # 差分があったときは差分を出力する
      - name: Show diff
        id: diff
        run: |
          result=$(git diff)
          echo "::set-output name=result::$result"
      - run: |
          REPO_NAME="${{ github.event.pull_request.head.repo.full_name }}"
          echo "REPO_NAME=${REPO_NAME}" >> "${GITHUB_ENV}"
      # 差分があったときは、コミットを作りpushする
      - name: Push
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        if: ${{ env.REPO_NAME == github.repository
          && steps.diff.outputs.result != '' }}
        run: |
          git config user.name "github-actions[bot]"
          EMAIL="41898282+github-actions[bot]@users.noreply.github.com"
          git config user.email "${EMAIL}"
          git add -u
          git commit -m "鳩は唐揚げ！(自動で直してあげたよ！)"
          REPO_URL="https://"
          REPO_URL+="${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/"
          REPO_URL+="${{github.repository}}.git"
          GITHUB_HEAD="HEAD:refs/heads/fix-version-${HEAD_REF}-python-version"
          git push -f "${REPO_URL}" "${GITHUB_HEAD}"
      - name: Set org name
        uses: actions/github-script@v6
        if: env.REPO_NAME == github.repository
        id: set_org_name
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script:
            return process.env.GITHUB_REPOSITORY.split('/')[0]
      - name: Get PullRequests
        uses: actions/github-script@v5
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        if: ${{ env.REPO_NAME == github.repository
          && steps.diff.outputs.result != '' }}
        id: get_pull_requests
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const HEAD_REF = process.env["HEAD_REF"]
            const pulls_list_params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "${{steps.set_org_name.outputs.result}}:fix-version-" + HEAD_REF + "-python-version",
              base: HEAD_REF,
              state: "open"
            }
            console.log("call pulls.list:", pulls_list_params)
            const pulls = await github.paginate(github.rest.pulls.list,
                                                pulls_list_params)
            return pulls.length
      # pushしたブランチでPRを作る
      - name: Create PullRequest
        uses: actions/github-script@v5
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        if: ${{ env.REPO_NAME == github.repository
          && steps.diff.outputs.result != ''
          && steps.get_pull_requests.outputs.result == 0 }}
        id: create_pull_request
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const HEAD_REF = process.env["HEAD_REF"]
            const number = "#${{github.event.pull_request.number}}"
            let title = ".python-versionを直してあげたよ！PRをマージしてね！ "
            title += number
            const pulls_create_params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "${{steps.set_org_name.outputs.result}}:fix-version-" + HEAD_REF + "-python-version",
              base: HEAD_REF,
              title,
              body: "鳩の唐揚げおいしい！😋😋😋 " + number
            }
            console.log("call pulls.create:", pulls_create_params)
            const create_pull_res = await github.rest.pulls.create(
                                      pulls_create_params
                                    )
            return create_pull_res.data.number
      - name: Assign a user
        uses: actions/github-script@v5
        if: ${{ env.REPO_NAME == github.repository
          && steps.diff.outputs.result != ''
          && steps.get_pull_requests.outputs.result == 0
          && github.event.pull_request.user.login != 'dependabot[bot]' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issues_add_assignees_params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{steps.create_pull_request.outputs.result}},
              assignees: ["${{github.event.pull_request.user.login}}"]
            }
            console.log("call issues.addAssignees:")
            console.log(issues_add_assignees_params)
            await github.rest.issues.addAssignees(issues_add_assignees_params)
      # 既にバージョン同期のPRがある状態で、手動でバージョンを修正した場合、バージョン同期のPRを閉じる
      - name: Close PullRequest
        uses: actions/github-script@v5
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        if: ${{ env.REPO_NAME == github.repository
          && steps.diff.outputs.result == '' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const HEAD_REF = process.env["HEAD_REF"]
            const head_name = "fix-version-" + HEAD_REF + "-python-version"
            const common_params = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }
            const pulls_list_params = {
              head: "${{steps.set_org_name.outputs.result}}:" + head_name,
              base: HEAD_REF,
              state: "open",
              ...common_params
            }
            console.log("call pulls.list:", pulls_list_params)
            const pulls = await github.paginate(github.rest.pulls.list,
                                                pulls_list_params)

            for (const pull of pulls) {
              const pulls_update_params = {
                pull_number: pull.number,
                state: "closed",
                ...common_params
              }
              console.log("call pulls.update:", pulls_update_params)
              await github.rest.pulls.update(pulls_update_params)
              const git_deleteRef_params = {
                ref: "heads/" + head_name,
                ...common_params
              }
              console.log("call git.deleteRef:", git_deleteRef_params)
              await github.rest.git.deleteRef(git_deleteRef_params)
            }
      - name: Exit
        if: ${{ steps.diff.outputs.result != '' }}
        run: exit 1
